# -*- coding: utf-8 -*-
"""Bank  Project Python Dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PyuNS7nhjb6IWG02AiTEdIa4E5vzjc-a

#Project: The Horizon Bank - Python Dictionaries

---

### Context

Decades before, most of the banks used to maintain the details of their customers in a record book or in an excel sheet in a computer. This is not so reliable as compared to today’s revolutionary growth of technology in almost all of the fields.

There is also a negative side in today’s growth of technology i.e. the increasing cyber crimes all over the world.

Do you know, in earlier days we need to stand in a long queue for hours in banks to deposit (a sum of money paid into a bank account) or withdraw (a sum of money withdrawn from a bank account) or to create a new bank account?
But nowadays with the growth of technology, users can create and maintain their bank account or pay their electric bills, phone bills by sitting in their homes. All they need is a smartphone and internet.

Now, a new bank called Horizon Bank decides to update their banking model from old excel sheets to the latest technology and require a sample project of a bank model. Let us help them in creating this bank application.

---

### Problem Statement 

In this project, you have to write a computer program to create an interactive bank application for the Horizon Bank. The application must have two simple functionalities:

1. Allow a customer to create a new bank account with their following personal details:

   - Full name

   - Permanent residential address

   - Personal or residential phone number

   - Valid government-issued identification 

   - Amount to be deposited to the account

2. Allow an existing customer of the bank to 

   - Check their bank balance
   
   - Withdraw some amount from their account provided that the withdrawal amount is less than the available bank balance
   
   - Deposit some amount to their account

---

### Project Requirements

1. Create an empty dictionary and store it in the `cust_data` variable. Also, create a list holding the attributes to be filled by a customer. Store the list in the `new_user_attributes` variable.

2. Create a function to add a new user to the 'cust_data' dictionary. Name the function as `new_user()`.

3. Create a function to get the account details of an existing user from the `cust_data` dictionary. Name the function as `existing_user()`.

4. Finally, create an infinite `while` loop to run the application.

---

#### 1. Customer Data

The data of all the customers needs to be stored in a Python dictionary. Let's call it `cust_data`. 

The key of the `cust_data` dictionary should be an account number of a customer. Its corresponding value should be another dictionary holding the personal details of a customer such as `name`, `address, email id` etc. as shown below. 

```
cust_data = {10011 : {'name': karthik, 
                      'address': 'C42, MG Complex, Sector-14, Vashi', 
                      'phone num': '9876543210',
                      'govt id': 'C12345Z',
                      'amount': 15999}}
``` 

Here, `10011` is the account number for Karthik's saving account. It acts as a key to the dictionary containing his details.

To add the personal details of another customer to the `cust_data` dictionary, you need to append it with existing data in the dictionary as shown below.

```
cust_data = {10011 : {'name': karthik, 
                      'address': 'C42, MG Complex, Sector-14, Vashi', 
                      'phone num': '9876543210',
                      'govt id': 'C12345Z',
                      'amount': 15999}, 
            100012 : {'name' : Hrithik, 
                      'address': B-910, Mandapeshwar Kripa, Borivalli, 
                      'phone num' : '9876543210',
                      'govt id': 'QL44345',
                      'amount': 13999}}
``` 

Next, you need to create a list holding the personal attributes of a customer, i.e., 

`['name', 'address', 'phone num', 'govt id', 'amount']`.
"""

# Creating the empty 'cust_data' dictionary and the 'new_user_attributes' list.
cust_data = {}
new_user_attributes = ['name', 'address', 'phone num', 'govt id', 'amount']

"""---

#### 2. Add New User

Create a function to add a new user to the `cust_data` dictionary. Name the function as `new_user()`. To do this, follow the steps described below.

**Step 1**: Create a random five-digit account number (ranging between 10000 to 99999) for a new customer using the `random` module. Make sure that it doesn't already exist in the `cust_data` dictionary.

**Step 2**: Create an empty list and store it in the `new_user_input` variable. This list is used to store the details of the user that is given in the `new_user_attribues` list.

**Step 3**: Prompt the user to enter all of their required details one-by-one and add  them to the list `new_user_input`. Make sure that the amount added to the list is an integer data-type.

**Step 4**: Create a dictionary for the new user and add it to the `cust_data` dictionary.

**Step 5**: Display the following message to the user.

  ```
  Your details are added successfully.
  Your account number is ABCDE 
  Please don't lose it.  
  ```
  where `ABCDE` is some randomly generated 5-digit account number (ranging between 10000 to 99999) for the new user.

**Note**: Write your code wherever you see the `Write your code here` comment.
"""

# The 'new_user()' function to add a new user to the 'cust_data' dictionary. 
import random

def new_user():
  # Step 1: Create a random five-digit account number and store it in 'acc_num' variable
  acc_num =random.randint(10000,99999)    # Write your code here
  while acc_num in cust_data.keys():
    acc_num=random.randint(10000,99999)
  
  # Step 2: Create an empty list and store it in the 'new_user_inputs' variable.
  # Write your code here
  new_user_inputs=[]


  # Step 3: Prompting the user to enter all of their required details one-by-one and add them to the list new_user_input.
  for i in range(len(new_user_attributes)):
    user_input = input("Enter " + new_user_attributes[i] + ":\n")
    if new_user_attributes[i] == 'amount':
      new_user_inputs.append(int(user_input))
    else:
      new_user_inputs.append(user_input)

  # Step 4: Creating a dictionary for the new user and add it to the cust_data dictionary.
  cust_data[acc_num] = dict(zip(new_user_attributes, new_user_inputs))

  # Step 5: Display the message on successfull account creation to the user.
  # Write your code here
  print("Your Details are added Sucessfully")
  print("Your Account number is",acc_num)

new_user()
cust_data

"""---

#### 3. Existing User

The function to get the account details of an existing user from the `cust_data` dictionary. Name the function as `existing_user()`. To do this, follow the steps described below.

**Step 1**: Prompt the user to enter their account number. Keep prompting until they enter their correct account number. For each invalid account number, print the following message to the user.

   ```
   Not found. Please enter your correct account number:
   ```

**Step 2**: Once the user has entered the correct account number, print the following message to the user.

   ```
   Welcome, user_name ! 
   Enter 1 to check your balance.
   Enter 2 to withdraw an amount.
   Enter 3 to deposit an amount.
   ```
  where `user_name` is the name of the existing user who entered his account number correctly in the first step.

**Step 3**: Prompt the user to enter either `1, 2` or `3`. Keep prompting until the user enters the valid input. For each invalid input, print the following message to the user.

   ```
   Invalid input! 
   Enter 1 to check your balance.
   Enter 2 to withdraw an amount.
   Enter 3 to deposit an amount.
   ```

**Step 4**: In the case of valid input:
  
   - If the user enters `1`, then display their available account balance.

   - Else if the user enters `2`, then prompt the user to enter the withdrawal amount by displaying the `Enter the amount to be withdrawn:` message.

     - If the withdrawal amount is greater than the available balance, then display the following message.

       ```
       Insufficient balance.
       Available balance: X
       ```

        where `X` is the available balance in the user's account.

     - Else, subtract the withdrawal amount from the available balance and replace the existing available amount with the updated amount in the `cust_data` dictionary. Also, print the following message.

       ```
       Withdrawal successful.
       Available Balance: Y
       ```

       where `Y` is the updated amount.

   - Else if the user enters `3`, then prompt them to enter the amount to be deposited to their account by displaying the `Enter the amount to be deposited:` message. Add the deposit amount to the available balance and update the new deposit amount in the `cust_data` dictionary. Also, display the following message.

     ```
     Deposit successful.
     Available Balance: Z
     ```

     where `Z` is the updated deposit amount.
"""

# The 'existing_user()' function to get the account details of an existing user from the 'cust_data' dictionary.
def existing_user():
  # Step 1: Ask the user to enter the existing account number and store it as an integer.
  acc_num = int(input("Enter Your Account Number: "))  # Write your code here
  while acc_num not in cust_data:
    acc_num = int(input("Not found. Please enter your correct account number:\n"))
    
  # Step 2: Print the welcome message to the user.
  # Write your code here
  print("Welcome, ",cust_data[acc_num]['name'],"!")
  print("Enter 1 to check your balance.\nEnter 2 to withdraw an amount.\nEnter 3 to deposit an amount.")

  # Step 3: Asking the user to select a valid choice. 
  user_choice = input()
  while user_choice not in ['1','2','3']:
    print("\nInvalid input!")
    print("Enter 1 to check your balance.\nEnter 2 to withdraw an amount.\nEnter 3 to deposit an amount.")
    user_choice = input()
  
  # Step 4:
  # If 'user_choice == 1' then display the account balance i.e. 'cust_data[acc_num]['amount']'
  if user_choice == '1':
    print("Available Balance ",cust_data[acc_num]['amount'])
    # Write your code here  
      
  # Else if 'user_choice == 2' then subtract the withdrawal amount from the available balance.
  elif user_choice == '2':
    amt = int(input("\nEnter the amount to be withdrawn:\n"))
    if amt > cust_data[acc_num]['amount']:
      print("\nInsufficient balance.\nAvailable balance:", cust_data[acc_num]['amount'])
    else:
      new_amt = int(cust_data[acc_num]['amount']) - amt
      cust_data[acc_num]['amount'] = new_amt
      print("\nWithdrawal successful.\nAvailable Balance:", cust_data[acc_num]['amount'])

  # Else if 'user_choice == 3' then add the deposit amount to the available balance.
  elif user_choice == '3':
    amt = int(input("\nEnter the amount to be deposited:\n"))
    new_amt = int(cust_data[acc_num]['amount']) + amt
    cust_data[acc_num]['amount'] = new_amt
    print("\nDeposit successful.\nAvailable Balance:", cust_data[acc_num]['amount'])

existing_user()

"""---

#### 4. Infinite `while` Loop 

Finally, create an infinite `while` loop to run the application. Inside the loop:

  1. Create a list of valid inputs, i.e., `'1', '2', '3'`

  2. Prompt the user to enter either `1, 2,` or `3` by displaying the following message.

     ```
     Welcome to the Horizon Bank!

     Enter 1 if you are a new customer.
     Enter 2 if you are an existing customer.
     Enter 3 to terminate the application.
     ```

     Keep prompting until the user enters the valid input. For each invalid input, print the following message to the user.

     ```
     Invalid input!
     Enter 1 if you are a new customer.
     Enter 2 if you are an existing customer.
     Enter 3 to terminate the application.
     ```

  3. If the user enters `1`, then create a new account for the user and get their personal details. After creating the account, terminate the application with the `Thank you, for banking with us!` message. 

  4. Else if the user enters 2, then display their account balance, reduce their balance or increase their balance depending on their further input. Afterwards, terminate the application with the `Thank you, for banking with us!` message. 

  5. Else if the user enters 3, then terminate the application with the `Thank you, for banking with us!` message.
"""

# Create an infinite while loop to run the application.
while True:
  valid_inputs = ['1','2','3']
  print("Welcome to the Horizon Bank!")
  print("\nEnter 1 if you are a new customer.\nEnter 2 if you are an existing customer.\nEnter 3 to terminate the application.") 

  user_choice = input()
  while user_choice not in ['1','2','3']:
    print("Invalid input!")
    print("Enter 1 if you are a new customer.\nEnter 2 if you are an existing customer.\nEnter 3 to terminate the application.\n")
    user_choice = input()

  # If the user enters 1, then call the 'new_user()' function (to create a new account for the user and get their personal details).
  # Write your code here
  if (user_choice=="1"):
    new_user()
    print("Thank You, for banking With Us !")
    break

  # Else If the user enters 2, then call the 'existing_user()' function.
  # Write your code here
  elif (user_choice=="2"):
    existing_user()
    print("Thank You, for banking With Us !")
    break

  # Else If the user enters 3, then terminate the application with the 'Thank you, for banking with us!' message. 
  elif (user_choice=="3"):
    print("Thank You, for banking With Us !")
    break

  # Write your code here

"""**Hints**:

- If the user enters `1` i.e. *New customer*, then invoke the `new_user()` function and break the infinite loop using the `break` keyword after displaying the thank you message (`'Thank you, for banking with us!'`).

- Else if the user enters `2` i.e. *Existing customer*, then invoke the `existing_user()` function and break the infinite loop using the `break` keyword after displaying the thank you message (`'Thank you, for banking with us!'`).

- Else if the user enters `3` i.e. *Quit application*, then display the thank you message (`‘Thank you, for banking with us!’`) and break the infinite loop using the `break` keyword.

---

---
"""